version: "3.8"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "80:80"
    environment:
      - REACT_APP_HOST=https://serveradminstaycation.herokuapp.com
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env